global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093" # Alertmanager address

rule_files:
  - "prometheus_alerting_rules.yml"

scrape_configs:
  - job_name: "metrics-service"
    static_configs:
      - targets: ["localhost:8000"]
