apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ai-service
spec:
  hosts:
    - "ai-service"
  http:
    - route:
        - destination:
            host: ai-service-stable
            subset: stable
          weight: 90
        - destination:
            host: ai-service-canary
            subset: canary
          weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ai-service
spec:
  host: ai-service
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
